Release
R2D2-2019/manual_control pull request #16
Opened 2019-07-05 12:46 UTC by b9a9s9

canbus integration for steering wheel on interface.

2019-07-05 14:36 UTC, JasperOosterbroek commented
@gerritvanos

2019-07-05 21:18 UTC, gerritvanos requested changes

2019-07-05 21:18 UTC, gerritvanos commented on code/headers/controller_interface.hpp
> +        controller_interface_c(int controller_id)
why is this parameter an int and the private variable an uint8_t

2019-07-05 21:18 UTC, gerritvanos commented on code/headers/dummy_controller.hpp
> +        dummy_controller_c(int controller_id)
same int comment

2019-07-05 21:18 UTC, gerritvanos commented on code/headers/manual_control.hpp
> +        std::array<unsigned char, 2> slider_list;
why an unsigned char is used here instead of an uint8_t do you store characters or just numbers?

2019-07-05 21:18 UTC, gerritvanos commented on code/headers/manual_control.hpp
> +            for (int x = button_a; x <= menu_right; x++) {
why is this an int, since it only counts up? or could button_a start below 0?

2019-07-05 21:18 UTC, gerritvanos commented on code/src/steering_wheel_controller.cpp
> +    unsigned char steering_wheel_controller_c::get_slider(sliders slider) {
why return a unsigned char when only using numbers please use a uint8_t

2019-07-06 19:14 UTC, florianhumblot requested changes

2019-07-06 19:14 UTC, florianhumblot commented on code/headers/steering_wheel_controller.hpp
> +    class steering_wheel_controller_c : public hwlib::pin_in,
Why are you inheriting from `hwlib::pin_in` ? you've made the `read` function private and it calls `refresh` on itself, so I'm not sure what is going on here...

2019-07-06 19:14 UTC, florianhumblot commented on code/src/joystick_value.cpp
> +    return (this->x >= rhs || this->y >= rhs);
are these comparison operators actually correct? 
Is a joystick value `greater than` the other or an int if only one of the two values is bigger?

2019-07-06 19:14 UTC, florianhumblot commented on code/src/joystick_value.cpp
> +    return (this->x >= rhs || this->y >= rhs);
same question for the other operator implementations below this one

2020-01-13 07:52 UTC, closed without merging